# -*- coding: utf-8 -*-
"""IAG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUkeSvNhdXbpWilvUGsaQ3dP6BP4_hA8
"""

# BIBLIOTECA DO TELEGRAM PARA CRIAR O BOT
!pip install pyTelegramBotAPI
!pip install pyTelegramBotAPI

# IMPORTA O ARQUIVO CSV (dados_imobiliaria.csv)
from google.colab import files
uploaded = files.upload()

# BIBLIOTECAS

# Biblioteca do Telegram
import telebot

# Biblioteca para manipular dados
import pandas as pd

# Modelo de Regressão Linear
from sklearn.linear_model import LinearRegression

# CONFIGURAÇÃO DO BOT
TOKEN = "tokenaqui"
bot = telebot.TeleBot(TOKEN)

# LEITURA DO CSV E TREINAMENTO DO MODELO

# Lê o arquivo
df = pd.read_csv("dados_imobiliaria.csv")

# X = variável de entrada (tamanho do imóvel)
X = df[["tamanho_m2"]]

# y = variável de saída (preço do imóvel)
y = df["preco_reais"]

# Cria e treina o modelo
modelo = LinearRegression()
modelo.fit(X, y)

# FUNÇÕES

# Formata um número para o padrão brasileiro de moeda.
def formatar_reais(valor):

    valor_formatado = f"{valor:,.2f}"
    valor_formatado = valor_formatado.replace(",", "X")
    valor_formatado = valor_formatado.replace(".", ",")
    valor_formatado = valor_formatado.replace("X", ".")
    return f"R$ {valor_formatado}"

# Recebe o tamanho do imóvel em m² e retorna o preço previsto pelo modelo.
def prever_preco(tamanho):

    nova_casa = pd.DataFrame({
        "tamanho_m2": [tamanho]
    })

    preco_previsto = modelo.predict(nova_casa)[0]
    return preco_previsto

# Retorna uma mensagem com os comandos disponíveis.
def mensagem_menu():

    return (
        "Comandos disponíveis:\n"
        "/start - iniciar atendimento\n"
        "/ajuda - ver instruções\n"
        "/comandos - listar comandos\n"
        "/novo - fazer nova simulação\n"
        "/encerrar - finalizar atendimento"
    )

# COMANDOS DO BOT

@bot.message_handler(commands=['start'])
def boas_vindas(mensagem):
    bot.reply_to(
        mensagem,
        "Olá! Eu sou o Corretor IAG da imobiliária KSR.\n\n"
        "Posso estimar o preço de um imóvel com base no tamanho em m².\n"
        "Envie apenas um número, como no exemplo abaixo:\n"
        "Exemplo: 120.\n\n"
        f"{mensagem_menu()}"
    )

@bot.message_handler(commands=['ajuda'])
def ajuda(mensagem):
    bot.reply_to(
        mensagem,
        "Como usar o corretor virtual:\n"
        "1. Envie apenas o tamanho do imóvel em m²\n"
        "2. Exemplo: 80\n"
        "3. Exemplo: 120\n"
        "4. Exemplo: 150\n\n"
        "Regras importantes:\n"
        "- Envie somente números\n"
        "- Use ponto ou vírgula se houver casas decimais\n"
        "- O valor deve ser maior que zero\n\n"
        "Exemplo válido: 95,5"
    )

@bot.message_handler(commands=['comandos'])
def comandos(mensagem):
    bot.reply_to(mensagem, mensagem_menu())

@bot.message_handler(commands=['novo'])
def novo_atendimento(mensagem):
    bot.reply_to(
        mensagem,
        "Perfeito! Envie o tamanho do imóvel em m² para eu calcular uma nova estimativa.\n"
        "Exemplo: 120."
    )

@bot.message_handler(commands=['encerrar'])
def encerrar(mensagem):
    bot.reply_to(
        mensagem,
        "Atendimento encerrado.\n"
        "Quando quiser fazer uma nova simulação, basta enviar /start."
    )

# TRATAMENTO DE ARQUIVOS NÃO SUPORTADOS
@bot.message_handler(content_types=['photo', 'document', 'audio', 'voice', 'sticker', 'video', 'location'])
def responder_formatos_nao_suportados(mensagem):
    bot.reply_to(
        mensagem,
        "No momento eu só consigo processar mensagens de texto com o tamanho do imóvel em m².\n"
        "Exemplo: 120."
    )

# TRATAMENTO DAS MENSAGENS DE TEXTO
@bot.message_handler(content_types=['text'])
def conversar(mensagem):
    texto = mensagem.text.strip().lower()

    try:
        # Troca vírgula por ponto para aceitar formatos como 95,5
        texto = texto.replace(",", ".")

        # Converte o texto para número
        tamanho = float(texto)

        # Valida se o valor é positivo
        if tamanho <= 0:
            bot.reply_to(
                mensagem,
                "Por favor, informe um valor maior que zero."
            )
            return

        # Validação simples para evitar valores absurdos
        if tamanho < 4 or tamanho > 1000:
            bot.reply_to(
                mensagem,
                "Por favor, informe um tamanho mais realista para o imóvel.\n"
                "Exemplo: 10, 120 ou 250."
            )
            return

        # Faz a previsão
        preco_previsto = prever_preco(tamanho)

        # Formata o valor em reais
        preco_formatado = formatar_reais(preco_previsto)

        # Responde ao usuário
        bot.reply_to(
            mensagem,
            f"Para um imóvel de {tamanho:.1f} m²,\n"
            f"o preço estimado é de {preco_formatado}.\n\n"
            "Deseja fazer outra simulação?\n"
            "Use /novo para calcular novamente ou /encerrar para finalizar."
        )

    except ValueError:
        bot.reply_to(
            mensagem,
            "Não consegui interpretar sua mensagem.\n"
            "Envie apenas o tamanho do imóvel em m².\n"
            "Exemplo: 120.\n\n"
            "Se precisar, use /ajuda."
        )

# INÍCIO DO BOT

print("Bot em execução...")
bot.infinity_polling()