# -*- coding: utf-8 -*-
"""IAG Expandido

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUkeSvNhdXbpWilvUGsaQ3dP6BP4_hA8
"""

# BIBLIOTECA DO TELEGRAM PARA CRIAR O BOT
!pip install pyTelegramBotAPI
!pip install pyTelegramBotAPI

# IMPORTA O ARQUIVO CSV (dados_imobiliaria.csv)
from google.colab import files
uploaded = files.upload()

# BIBLIOTECAS

# Biblioteca do Telegram
import telebot
# Biblioteca para manipular dados
import pandas as pd
# Modelo de Regressão Linear
from sklearn.linear_model import LinearRegression

# CONFIGURAÇÃO DO BOT
TOKEN = "TOKEN AQUI"
bot = telebot.TeleBot(TOKEN)

# LEITURA DO CSV E PREPARAÇÃO DOS DADOS

# Lê o arquivo CSV expandido
df = pd.read_csv("dados_imobiliaria_expandido.csv")

# Transforma colunas categóricas (texto) em colunas numéricas
df_modelo = pd.get_dummies(
    df,
    columns=["tipo_imovel", "subtipo_apartamento", "zona"]
)

# Define as variáveis de entrada do modelo
colunas_para_remover = [
    "preco_reais",
    "preco_original",
    "fator_tipo",
    "fator_subtipo",
    "fator_zona",
    "padrao_calculado"
]

# Remove apenas as colunas que realmente existirem no CSV
colunas_existentes_para_remover = [
    coluna for coluna in colunas_para_remover if coluna in df_modelo.columns
]

X = df_modelo.drop(columns=colunas_existentes_para_remover)

# Define a variável alvo
y = df_modelo["preco_reais"]

# Cria o modelo de regressão linear
modelo = LinearRegression()

# Treina o modelo
modelo.fit(X, y)

# CONTROLE DE ETAPAS DOS USUÁRIOS

# Dicionário que guarda em que etapa da conversa cada usuário está
estado_usuarios = {}

# FUNÇÕES AUXILIARES
def formatar_reais(valor):
    """
    Formata um número para o padrão brasileiro de moeda.
    """
    valor_formatado = f"{valor:,.2f}"
    valor_formatado = valor_formatado.replace(",", "X")
    valor_formatado = valor_formatado.replace(".", ",")
    valor_formatado = valor_formatado.replace("X", ".")
    return f"R$ {valor_formatado}"

def mensagem_menu():
    """
    Retorna a mensagem com os comandos disponíveis.
    """
    return (
        "Comandos disponíveis:\n"
        "/start - iniciar atendimento\n"
        "/ajuda - ver instruções\n"
        "/comandos - listar comandos\n"
        "/novo - fazer nova simulação\n"
        "/sobre - saber como o bot funciona\n"
        "/encerrar - finalizar atendimento"
    )

def iniciar_fluxo(chat_id):
    """
    Reinicia o atendimento do usuário.
    """
    estado_usuarios[chat_id] = {
        "etapa": "tipo_imovel",
        "tipo": None,
        "subtipo": "nao_se_aplica",
        "zona": None
    }

def limpar_entrada(texto):
    """
    Limpa e padroniza a entrada da metragem.
    Aceita exemplos como:
    120 - 95,5 - 95.5 - 120 m2 - 120 m²
    """
    texto = texto.strip().lower()
    texto = texto.replace("m²", "")
    texto = texto.replace("m2", "")
    texto = texto.replace(",", ".")
    return texto.strip()

def validar_tamanho(tamanho):
    """
    Valida se o tamanho informado faz sentido.
    """
    if tamanho <= 0:
        return "Por favor, informe um valor maior que zero."

    if tamanho < 4 or tamanho > 100000:
        return (
            "Por favor, informe um tamanho mais realista para o imóvel.\n"
            "Exemplo: 10, 120, 250 ou 1000."
        )

    return None

def classificar_padrao_imovel(tipo, subtipo, tamanho):
    """
    Classifica o padrão do imóvel com base no tipo, subtipo e metragem.

    CASA
    - até 149,9 m² -> casa compacta
    - 150 a 299,9 m² -> casa padrão
    - 300 a 599,9 m² -> casa de alto padrão
    - 600 a 999,9 m² -> mansão
    - 1000 m² ou mais -> mansão de luxo

    APARTAMENTO COMUM
    - até 69,9 m² -> apartamento compacto
    - 70 a 149,9 m² -> apartamento padrão
    - 150 a 299,9 m² -> apartamento de alto padrão
    - 300 a 499,9 m² -> apartamento de luxo
    - 500 m² ou mais -> apartamento de luxo extremo

    COBERTURA
    - até 149,9 m² -> cobertura compacta
    - 150 a 299,9 m² -> cobertura de alto padrão
    - 300 a 499,9 m² -> cobertura de luxo
    - 500 m² ou mais -> cobertura de luxo extremo
    """

    if tipo == "casa":
        if tamanho < 150:
            return "casa compacta"
        elif tamanho < 300:
            return "casa padrão"
        elif tamanho < 600:
            return "casa de alto padrão"
        elif tamanho < 1000:
            return "mansão"
        else:
            return "mansão de luxo"

    if tipo == "apartamento":
        if subtipo == "cobertura":
            if tamanho < 150:
                return "cobertura compacta"
            elif tamanho < 300:
                return "cobertura de alto padrão"
            elif tamanho < 500:
                return "cobertura de luxo"
            else:
                return "cobertura de luxo extremo"
        else:
            if tamanho < 70:
                return "apartamento compacto"
            elif tamanho < 150:
                return "apartamento padrão"
            elif tamanho < 300:
                return "apartamento de alto padrão"
            elif tamanho < 500:
                return "apartamento de luxo"
            else:
                return "apartamento de luxo extremo"

    return "imóvel"

def faixa_imovel(tipo, subtipo, tamanho):
    """
    Retorna uma observação mais natural com base na classificação do imóvel.
    """
    classificacao = classificar_padrao_imovel(tipo, subtipo, tamanho)

    observacoes = {
        "casa compacta": "Esse parece ser um imóvel residencial mais compacto.",
        "casa padrão": "Esse imóvel está dentro de uma faixa bastante comum no mercado residencial.",
        "casa de alto padrão": "Estamos falando de uma casa com metragem acima da média.",
        "mansão": "Estamos falando de uma mansão com padrão elevado.",
        "mansão de luxo": "Estamos falando de uma mansão de luxo, com metragem muito acima do padrão comum.",
        "apartamento compacto": "Esse parece ser um apartamento mais compacto e funcional.",
        "apartamento padrão": "Esse apartamento está dentro de uma faixa bastante comum no mercado.",
        "apartamento de alto padrão": "Estamos falando de um apartamento de alto padrão.",
        "apartamento de luxo": "Estamos falando de um apartamento de luxo.",
        "apartamento de luxo extremo": "Estamos falando de um apartamento de luxo extremo, muito acima do padrão usual.",
        "cobertura compacta": "Estamos falando de uma cobertura compacta, mas com perfil diferenciado.",
        "cobertura de alto padrão": "Estamos falando de uma cobertura de alto padrão.",
        "cobertura de luxo": "Estamos falando de uma cobertura de luxo.",
        "cobertura de luxo extremo": "Estamos falando de uma cobertura de luxo extremo, muito acima do padrão usual."
    }

    return observacoes.get(
        classificacao,
        "Esse imóvel possui características específicas de metragem."
    )

def montar_entrada_modelo(tamanho, tipo, subtipo, zona):
    """
    Monta uma linha de entrada com exatamente as mesmas colunas usadas no treino.
    """

    # Cria um dicionário com todas as colunas zeradas
    entrada = {coluna: 0 for coluna in X.columns}

    # Preenche a metragem
    if "tamanho_m2" in entrada:
        entrada["tamanho_m2"] = tamanho

    # Marca o tipo do imóvel escolhido
    coluna_tipo = f"tipo_imovel_{tipo}"
    if coluna_tipo in entrada:
        entrada[coluna_tipo] = 1

    # Marca o subtipo do apartamento
    coluna_subtipo = f"subtipo_apartamento_{subtipo}"
    if coluna_subtipo in entrada:
        entrada[coluna_subtipo] = 1

    # Marca a zona escolhida
    coluna_zona = f"zona_{zona}"
    if coluna_zona in entrada:
        entrada[coluna_zona] = 1

    # Converte para DataFrame com uma única linha
    return pd.DataFrame([entrada])

def prever_preco(tamanho, tipo, subtipo, zona):
    """
    Realiza a previsão.
    """
    entrada_modelo = montar_entrada_modelo(tamanho, tipo, subtipo, zona)
    preco_previsto = modelo.predict(entrada_modelo)[0]
    return preco_previsto

def montar_resposta_estimativa(tipo, subtipo, zona, tamanho, preco_formatado):
    """
    Monta a resposta final da simulação.
    """
    classificacao = classificar_padrao_imovel(tipo, subtipo, tamanho)
    observacao = faixa_imovel(tipo, subtipo, tamanho)

    return (
        f"Perfeito! Para um(a) {classificacao} de {tamanho:.1f} m², "
        f"localizado(a) em {zona.title()},\n"
        f"o preço estimado é de {preco_formatado}.\n\n"
        f"{observacao}\n\n"
        "Deseja fazer outra simulação?\n"
        "Use /novo para calcular novamente ou /encerrar para finalizar."
    )

# COMANDOS DO BOT
@bot.message_handler(commands=['start'])
def boas_vindas(mensagem):
    """
    Inicia o atendimento e pergunta o tipo do imóvel.
    """
    chat_id = mensagem.chat.id
    iniciar_fluxo(chat_id)

    bot.reply_to(
        mensagem,
        "Olá! Eu sou o Corretor IAG Expandido da imobiliária KSR.\n\n"
        "Agora posso estimar o preço de um imóvel considerando:\n"
        "- tipo do imóvel\n"
        "- zona\n"
        "- tamanho em m²\n\n"
        "Primeiro, escolha o tipo de imóvel:\n"
        "1 - Casa\n"
        "2 - Apartamento\n\n"
        f"{mensagem_menu()}"
    )

@bot.message_handler(commands=['ajuda'])
def ajuda(mensagem):
    """
    Explica como usar o bot.
    """
    bot.reply_to(
        mensagem,
        "Como usar o corretor virtual:\n"
        "1. Inicie com /start\n"
        "2. Escolha o tipo do imóvel\n"
        "3. Se for apartamento, escolha o subtipo\n"
        "4. Escolha a zona\n"
        "5. Envie a metragem do imóvel em m²\n\n"
        "Exemplos válidos de metragem:\n"
        "- 80\n"
        "- 95,5\n"
        "- 120 m²\n\n"
        "Tipos disponíveis:\n"
        "- Casa\n"
        "- Apartamento\n\n"
        "Subtipos para apartamento:\n"
        "- Comum\n"
        "- Cobertura\n\n"
        "Observação:\n"
        "O padrão do imóvel é identificado automaticamente com base na metragem.\n\n"
        "Zonas disponíveis:\n"
        "- Zona Sul\n"
        "- Zona Norte\n"
        "- Zona Oeste\n"
        "- Zona Leste\n"
        "- Centro"
    )

@bot.message_handler(commands=['comandos'])
def comandos(mensagem):
    """
   Lista os comandos disponíveis.
    """
    bot.reply_to(mensagem, mensagem_menu())

@bot.message_handler(commands=['novo'])
def novo_atendimento(mensagem):
    """
    Reinicia a simulação do zero.
    """
    chat_id = mensagem.chat.id
    iniciar_fluxo(chat_id)

    bot.reply_to(
        mensagem,
        "Perfeito! Vamos começar uma nova simulação.\n\n"
        "Escolha o tipo do imóvel:\n"
        "1 - Casa\n"
        "2 - Apartamento"
    )

@bot.message_handler(commands=['sobre'])
def sobre(mensagem):
    """
    Explica como o bot funciona agora.
    """
    bot.reply_to(
        mensagem,
        "Eu utilizo Regressão Linear para estimar preços de imóveis.\n"
        "Agora o cálculo considera metragem, tipo do imóvel, subtipo do apartamento e zona.\n"
        "Essas informações são aprendidas a partir de uma base de dados expandida."
    )

@bot.message_handler(commands=['encerrar'])
def encerrar(mensagem):
    """
    Encerra o atendimento do usuário.
    """
    chat_id = mensagem.chat.id

    if chat_id in estado_usuarios:
        del estado_usuarios[chat_id]

    bot.reply_to(
        mensagem,
        "Atendimento encerrado.\n"
        "Quando quiser fazer uma nova simulação, basta enviar /start."
    )

# TRATAMENTO DE ARQUIVOS NÃO SUPORTADOS
@bot.message_handler(
    content_types=['photo', 'document', 'audio', 'voice', 'sticker', 'video', 'location']
)
def responder_formatos_nao_suportados(mensagem):
    """
    Responde quando o usuário envia algo que não seja texto.
    """
    bot.reply_to(
        mensagem,
        "No momento eu só consigo processar mensagens de texto.\n"
        "Envie /start para iniciar uma simulação."
    )

# TRATAMENTO DAS MENSAGENS DE TEXTO
@bot.message_handler(content_types=['text'])
def conversar(mensagem):
    """
    Controla as etapas da conversa:
    1. Tipo do imóvel
    2. Subtipo do apartamento (se necessário)
    3. Zona
    4. Metragem
    """
    chat_id = mensagem.chat.id
    texto_original = mensagem.text.strip()
    texto = texto_original.lower()

    # Se o usuário ainda não tiver um fluxo iniciado, iniciamos automaticamente
    if chat_id not in estado_usuarios:
        iniciar_fluxo(chat_id)

    etapa = estado_usuarios[chat_id]["etapa"]

    # ETAPA 1 - ESCOLHER TIPO DO IMÓVEL
    if etapa == "tipo_imovel":
        if texto in ["1", "casa"]:
            estado_usuarios[chat_id]["tipo"] = "casa"
            estado_usuarios[chat_id]["subtipo"] = "nao_se_aplica"
            estado_usuarios[chat_id]["etapa"] = "zona"

            bot.reply_to(
                mensagem,
                "Ótimo! Agora escolha a zona do imóvel:\n"
                "1 - Zona Sul\n"
                "2 - Zona Norte\n"
                "3 - Zona Oeste\n"
                "4 - Zona Leste\n"
                "5 - Centro"
            )
            return

        elif texto in ["2", "apartamento", "apto"]:
            estado_usuarios[chat_id]["tipo"] = "apartamento"
            estado_usuarios[chat_id]["etapa"] = "subtipo_apartamento"

            bot.reply_to(
                mensagem,
                "Perfeito! Agora escolha o subtipo do apartamento:\n"
                "1 - Comum\n"
                "2 - Cobertura"
            )
            return

        else:
            bot.reply_to(
                mensagem,
                "Por favor, escolha uma opção válida:\n"
                "1 - Casa\n"
                "2 - Apartamento"
            )
            return

    # ETAPA 2 - ESCOLHER SUBTIPO DO APARTAMENTO
    if etapa == "subtipo_apartamento":
        if texto in ["1", "comum", "apartamento comum"]:
            estado_usuarios[chat_id]["subtipo"] = "comum"
            estado_usuarios[chat_id]["etapa"] = "zona"

            bot.reply_to(
                mensagem,
                "Ótimo! Agora escolha a zona do imóvel:\n"
                "1 - Zona Sul\n"
                "2 - Zona Norte\n"
                "3 - Zona Oeste\n"
                "4 - Zona Leste\n"
                "5 - Centro"
            )
            return

        elif texto in ["2", "cobertura"]:
            estado_usuarios[chat_id]["subtipo"] = "cobertura"
            estado_usuarios[chat_id]["etapa"] = "zona"

            bot.reply_to(
                mensagem,
                "Perfeito! Agora escolha a zona do imóvel:\n"
                "1 - Zona Sul\n"
                "2 - Zona Norte\n"
                "3 - Zona Oeste\n"
                "4 - Zona Leste\n"
                "5 - Centro"
            )
            return

        else:
            bot.reply_to(
                mensagem,
                "Por favor, escolha uma opção válida:\n"
                "1 - Comum\n"
                "2 - Cobertura"
            )
            return

    # ETAPA 3 - ESCOLHER ZONA
    if etapa == "zona":
        mapa_zonas = {
            "1": "zona sul",
            "2": "zona norte",
            "3": "zona oeste",
            "4": "zona leste",
            "5": "centro",
            "zona sul": "zona sul",
            "zona norte": "zona norte",
            "zona oeste": "zona oeste",
            "zona leste": "zona leste",
            "centro": "centro",
            "sul": "zona sul",
            "norte": "zona norte",
            "oeste": "zona oeste",
            "leste": "zona leste"
        }

        if texto in mapa_zonas:
            estado_usuarios[chat_id]["zona"] = mapa_zonas[texto]
            estado_usuarios[chat_id]["etapa"] = "metragem"

            bot.reply_to(
                mensagem,
                "Perfeito! Agora envie o tamanho do imóvel em m².\n"
                "Exemplo: 120"
            )
            return

        else:
            bot.reply_to(
                mensagem,
                "Por favor, escolha uma zona válida:\n"
                "1 - Zona Sul\n"
                "2 - Zona Norte\n"
                "3 - Zona Oeste\n"
                "4 - Zona Leste\n"
                "5 - Centro"
            )
            return

    # ETAPA 4 - INFORMAR METRAGEM E CALCULAR
    if etapa == "metragem":
        try:
            # Limpa a entrada para aceitar formatos como 95,5 ou 120 m²
            texto_limpo = limpar_entrada(texto_original)

            # Converte a metragem para número
            tamanho = float(texto_limpo)

            # Valida se a metragem é aceitável
            mensagem_erro = validar_tamanho(tamanho)
            if mensagem_erro:
                bot.reply_to(mensagem, mensagem_erro)
                return

            # Recupera as escolhas anteriores do usuário
            tipo = estado_usuarios[chat_id]["tipo"]
            subtipo = estado_usuarios[chat_id]["subtipo"]
            zona = estado_usuarios[chat_id]["zona"]

            # Faz a previsão usando todas as variáveis
            preco_previsto = prever_preco(tamanho, tipo, subtipo, zona)

            # Formata o valor para o padrão brasileiro
            preco_formatado = formatar_reais(preco_previsto)

            # Monta a resposta final
            resposta = montar_resposta_estimativa(
                tipo,
                subtipo,
                zona,
                tamanho,
                preco_formatado
            )

            # Envia a resposta ao usuário
            bot.reply_to(mensagem, resposta)

        except ValueError:
            bot.reply_to(
                mensagem,
                "Não consegui interpretar sua mensagem.\n"
                "Envie apenas o tamanho do imóvel em m².\n"
                "Exemplos válidos: 80, 95,5 ou 120 m².\n\n"
                "Se precisar, use /ajuda."
            )

# INÍCIO DO BOT

print("Bot em execução...")
bot.infinity_polling()